FROM tensorflow/tensorflow:1.12.0-gpu-py3

#docker 1
RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN apt-get install libsm6 libxext6 libxrender-dev -y
RUN pip3 install numpy
RUN pip3 install opencv-python
RUN pip3 install grpcio
RUN pip3 install protobuf

#docker 2
RUN pip3 install scipy
RUN pip3 install imutils
RUN pip3 install cMake
RUN pip3 install dlib

#docker 3
RUN pip3 install scikit-image
RUN pip3 install Cython
RUN pip3 install pycocotools
RUN pip3 install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
RUN pip3 install keras
RUN pip3 install imgaug
#docker 4 none
#add
ADD container1 /container/container1
ADD container2 /container/container2
ADD container3 /container/container3
ADD container4 /container/container4
ADD part1 /container/part1

# for RAFT !!!!! IMPORTANT!!!!!!
RUN pip3 install pyyaml

RUN apt-get install git -y

RUN pip3 install git+https://github.com/ucbrise/clipper.git@develop#subdirectory=clipper_admin


RUN apt-get update -qq \
      && apt-get install -y -qq libzmq5 libzmq5-dev redis-server libsodium18 build-essential

ENV PIP_DEFAULT_TIMEOUT=100
RUN pip install --upgrade pip

RUN pip install -q cloudpickle==0.5.* pyzmq==17.0.* prometheus_client==0.1.* \
    pyyaml>=4.2b1 jsonschema==2.6.* redis==2.10.* psutil==5.4.* flask==0.12.2 

ADD closure.py /container
ADD rpc.py /container
ADD metrics_config.yaml /container
ADD main.py /container

# /container nows contains: 
# c0_entryContainer c1_speechRecognition/ c2_imageCaptionGenerator/ c3_nlpMappingGenerator/ c4_questionAnswering/ main.py

# Crucial
WORKDIR /container


CMD ["python3","/container/closure.py"]

Expose 10000

# docker build -f ./FatigueDetections/Dockerfile_main -t detection:main .
# docker run --runtime=nvidia -p 10000:10000 -it detection:main
# docker run --runtime=nvidia -d -p 10000:10000 -it detection:main


